DEBUG 2021-04-02 12:15:16.119 UTC: 	 CRAB Client version: v3.210127
DEBUG 2021-04-02 12:15:16.120 UTC: 	 Running on: Linux cmslpc139.fnal.gov 3.10.0-1160.15.2.el7.x86_64 #1 SMP Tue Feb 2 08:13:55 CST 2021 x86_64 x86_64 x86_64 GNU/Linux - Scientific Linux 7.9 (Nitrogen)
DEBUG 2021-04-02 12:15:16.120 UTC: 	 Executing command: 'status'
DEBUG 2021-04-02 12:15:16.120 UTC: 	 Found CRAB cache file /uscms/home/cannaert/.crab3
ERROR 2021-04-02 12:15:16.124 UTC: 	 Error: Suu8TeV_chi1TeV/CMSSW_10_6_17_patch1/src/crab_projects/crab_MC_prod_Suu6TeV_chi1TeV_DIGI_0001/ is not a valid CRAB project directory.
ERROR 2021-04-02 12:15:16.124 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210127.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210127.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210127.00/lib/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210127.00/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210127.00/lib/CRABClient/Commands/SubCommand.py", line 639, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: Suu8TeV_chi1TeV/CMSSW_10_6_17_patch1/src/crab_projects/crab_MC_prod_Suu6TeV_chi1TeV_DIGI_0001/ is not a valid CRAB project directory.
INFO 2021-04-02 12:15:16.127 UTC: 	 Log file is /uscms_data/d3/cannaert/UL2018_genproduction/crab.log
